# Generated by Django 5.1.5 on 2025-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название статьи", max_length=150, verbose_name="Название"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Это произведение будет лучшим!", null=True, verbose_name="Текст"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="article/preview",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Введите дату написания статьи", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, help_text="Опубликована ли статья?", verbose_name="Публикация"),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
