# Generated by Django 4.2.2 on 2025-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Опубликована ли продукт?", verbose_name="Признак публикации"
            ),
        ),
    ]
