# Generated by Django 5.1.4 on 2025-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Дата создании записи о продукте",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Дата внесения последнего изменения",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(
                blank=True,
                help_text="Введите цену продукта",
                null=True,
                verbose_name="Цена продукта",
            ),
        ),
    ]
