# Generated by Django 4.2.2 on 2025-02-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Опубликован ли продукт?", verbose_name="Признак публикации"
            ),
        ),
    ]
